services:

  app_proxy:
    environment:
      # Format: <app-id>_<docker-service-name>_1
      APP_HOST: ckryza-dpmp_dpmp_1
      APP_PORT: 8855

  dpmp:
    image: ghcr.io/ckryza/dpmpv2:3.0.0
    restart: on-failure
    environment:
      DPMP_CONFIG: /dpmp/config_v2.json
    volumes:
      - ${APP_DATA_DIR}/data/dpmp:/dpmp
    ports:
      - "3351:3351"
      - "9210:9210"
      - "8855:8855"


